# Generated by Django 4.0.3 on 2022-03-17 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_alter_histories_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histories',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
