# Generated by Django 4.0.3 on 2022-03-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True)),
                ('category', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('price', models.FloatField()),
                ('price_on_sale', models.FloatField()),
                ('discount', models.FloatField()),
                ('sale', models.BooleanField()),
                ('owner', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity_stock', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
